//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAR_WARS_LIBRARY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historique
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> DateDeH { get; set; }
        public Nullable<int> WookieID { get; set; }
        public Nullable<int> DroideID { get; set; }
        public Nullable<int> batailleID { get; set; }
        public Nullable<int> pointsDeVie { get; set; }
    
        public virtual Bataille Bataille { get; set; }
        public virtual Droide Droide { get; set; }
        public virtual Wookie Wookie { get; set; }
    }
}
