//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STAR_WARS_LIBRARY
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wookie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wookie()
        {
            this.Combat = new HashSet<Combat>();
            this.Historique = new HashSet<Historique>();
        }
    
        public int ID { get; set; }
        public string Nom { get; set; }
        public Nullable<System.DateTime> DateDeN { get; set; }
        public Nullable<bool> Sexe { get; set; }
        public Nullable<int> PlaneteID { get; set; }
    
        public virtual Planete Planete { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Combat> Combat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Historique> Historique { get; set; }
    }
}
